import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';
import ora from 'ora';

interface InitOptions {
  database: string;
  push: string;
}

const TEMPLATE_ENV = `# OpenMDM Configuration
# Generated by openmdm init

# Database Configuration
DATABASE_URL=postgres://user:password@localhost:5432/openmdm

# Push Notification Configuration
PUSH_PROVIDER={{push}}

# FCM Configuration (if using FCM)
# GOOGLE_APPLICATION_CREDENTIALS=./firebase-service-account.json
# FIREBASE_PROJECT_ID=your-project-id

# MQTT Configuration (if using MQTT)
# MQTT_BROKER_URL=mqtt://localhost:1883
# MQTT_USERNAME=
# MQTT_PASSWORD=

# Security
DEVICE_SECRET={{deviceSecret}}
JWT_SECRET={{jwtSecret}}

# Server
PORT=3000
SERVER_URL=http://localhost:3000
`;

const TEMPLATE_CONFIG = `import { createMDM } from '@openmdm/core';
import { drizzleAdapter } from '@openmdm/drizzle-adapter';
{{pushImport}}
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

// Database connection
const connection = postgres(process.env.DATABASE_URL!);
const db = drizzle(connection);

// Create MDM instance
export const mdm = createMDM({
  database: drizzleAdapter(db),
  {{pushConfig}}
  enrollment: {
    deviceSecret: process.env.DEVICE_SECRET!,
    autoEnroll: true,
  },
  auth: {
    deviceTokenSecret: process.env.JWT_SECRET!,
  },
  serverUrl: process.env.SERVER_URL,
});
`;

export async function initProject(options: InitOptions): Promise<void> {
  console.log(chalk.blue('\\n🚀 Initializing OpenMDM Project\\n'));

  // Interactive prompts
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: 'my-mdm-server',
    },
    {
      type: 'list',
      name: 'database',
      message: 'Database:',
      choices: ['postgres', 'mysql', 'sqlite'],
      default: options.database,
    },
    {
      type: 'list',
      name: 'push',
      message: 'Push notification provider:',
      choices: ['fcm', 'mqtt', 'polling'],
      default: options.push,
    },
    {
      type: 'confirm',
      name: 'createFiles',
      message: 'Create configuration files?',
      default: true,
    },
  ]);

  if (!answers.createFiles) {
    console.log(chalk.yellow('\\nSkipping file creation.'));
    return;
  }

  const spinner = ora('Creating configuration files...').start();

  try {
    // Generate secrets
    const deviceSecret = generateSecret(32);
    const jwtSecret = generateSecret(64);

    // Create .env file
    const envContent = TEMPLATE_ENV
      .replace('{{push}}', answers.push)
      .replace('{{deviceSecret}}', deviceSecret)
      .replace('{{jwtSecret}}', jwtSecret);

    await fs.writeFile('.env.example', envContent);
    spinner.succeed('Created .env.example');

    // Create config file
    let pushImport = '';
    let pushConfig = '';

    switch (answers.push) {
      case 'fcm':
        pushImport = "import { fcmPushAdapterFromEnv } from '@openmdm/push-fcm';";
        pushConfig = 'push: fcmPushAdapterFromEnv(),';
        break;
      case 'mqtt':
        pushImport = "import { mqttPushAdapterFromEnv } from '@openmdm/push-mqtt';";
        pushConfig = 'push: mqttPushAdapterFromEnv(),';
        break;
      default:
        pushConfig = '// No push provider configured';
    }

    const configContent = TEMPLATE_CONFIG
      .replace('{{pushImport}}', pushImport)
      .replace('{{pushConfig}}', pushConfig);

    await fs.mkdir('src', { recursive: true });
    await fs.writeFile('src/mdm.ts', configContent);
    spinner.succeed('Created src/mdm.ts');

    // Print next steps
    console.log(chalk.green('\\n✅ OpenMDM project initialized!\\n'));
    console.log(chalk.white('Next steps:'));
    console.log(chalk.gray('  1. Copy .env.example to .env and configure'));
    console.log(chalk.gray('  2. Run database migrations: openmdm migrate'));
    console.log(chalk.gray('  3. Start your server and integrate the MDM instance'));
    console.log('');
  } catch (error) {
    spinner.fail('Failed to create files');
    console.error(chalk.red(error));
  }
}

function generateSecret(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  const randomArray = new Uint8Array(length);
  crypto.getRandomValues(randomArray);
  for (let i = 0; i < length; i++) {
    result += chars[randomArray[i] % chars.length];
  }
  return result;
}
